TRIGGER_DISTANCE_MM = 1500

PROCESS_W = 480

YOLO_INTERVAL = 1.0
YOLO_MODEL_PATH = "/home/nvidia/RosCV/yolov8s.pt"

RAY_STEP_MM = 60
RAY_MAX_MM = 4000
HIT_3D_THRESHOLD_MM = 70
RAY_START_OFFSET_MM = 120
LOCAL_CLOUD_RADIUS = 3
LOCAL_CLOUD_MIN_POINTS = 5
LOCAL_CLOUD_DEPTH_BAND_MM = 180
LOCAL_CLOUD_HIT_THRESHOLD_MM = 65
RERAYCAST_MOVE_THRESHOLD_MM = 40
RERAYCAST_ANGLE_THRESHOLD_DEG = 4
POINT_CONFIRM_FRAMES = 12
CAPTURE_DIR = "rviz_captured_images"
LATEST_FRAME_PATH = "rviz_captured_images/latest.jpg"

SMOOTH_ALPHA_2D = 0.45
SMOOTH_ALPHA_DEPTH = 0.45
SMOOTH_ALPHA_DIR = 0.4
